### PR TITLE
boshrelease template - use bosh2, use manifests/name.yml for deploy, testflight-pr job for pull requests

### PR DESCRIPTION
**Pull request by drnic**
See https://drive.google.com/file/d/0B-mhzqwGPE0XNXI1bmVZRElhbWs/view?usp=sharing as an introduction to this upgraded `boshrelease` template.

The slides' instructions assume this PR is merged into master. To try the branch:

```
git clone https://github.com/drnic/pipeline-templates -b bosh2
```

The pipeline + release created in the slide deck are:

* https://ci.starkandwayne.com/teams/main/pipelines/mything-boshrelease?groups=mything-boshrelease
* https://github.com/cloudfoundry-community/mything-boshrelease

`shipit` job now posts a happy message to slack:

screen shot 2017-08-23 at 2 58 48 pm

### CODE REVIEW

**Comment by norman-abramovitz** [comment]
So no more support for bosh v1

**Comment by drnic** [comment]
@norman-abramovitz bosh1 CLI users can still use boshreleases published by this CI pipeline; is that your concern, or are you thinking about something else?

**Comment by drnic** [comment]
@norman-abramovitz oh, I've thought of one concern - this new pipeline will stop using/testing `templates/make_manifest warden` templates; and instead look for a `manifests/name.yml` with optional operator files + optional variables. bosh1 users can continue to use bosh1/spruce manifests; but they won't be tested via the pipeline.

Which boshrelease repos might you be most concerned about to continue testing  `templates/make_manifest warden` templates?

**Comment by drnic** [comment]
For projects that wish to maintain a branch for their old `templates/make_manifest`/bosh1 templates, then perhaps look to the example by @jhunt with https://github.com/starkandwayne/shield-boshrelease/tree/6.x/ci - the `6.x` branch contains the old pipeline scripts that use bosh1 and use `make_manifest`

**Comment by geofffranks** [comment]
@drnic Is this the same as what you added to the haproxy-boshrelease?

**Comment by drnic** [comment]
@geofffranks yes

**Pull request merged**
