### PR TITLE
Various improvements on the BOSH Release pipeline template (on top of #41)

### PR DESCRIPTION
**Pull request by bgandon**
Hi,
As a preliminary notice, this PR is based on top of the `update-syntax` and `factor-image-resource` branches, already submitted in #40 and #41.
Thus the diffs here include those of #40 and #41 until those PR are merged.

In this PR, I'm suggesting various improvements from the Gstack experience with the BOSH Release pipeline template.

Each single improvement is isolated in its own commit. I let you choose which ones make sense for you, if not all.

Best,

### CODE REVIEW

**Comment by drnic** [comment]
Thanks for all the changes. I look forward to merging after your changes/discussions from review.

**Comment by bgandon** [comment]
Oh, sorry, I just realize had already submitted my improvements back in May.

But here I submitted more of those, so we could forget about #32. By the way, I've answered your question there.

**Comment by drnic** [comment]
@bgandon thanks for the updated PR(s). I'm busy this week; will review them next week. 👍

**Comment by bgandon** [comment]
No problem. I just submitted a bugfix BTW. Don't hesitate to ask me to rebase these improvements here on top of the bugfix, if necessary.

**Review by norman-abramovitz — APPROVED** [review]
Approved

**Pull request merged**
